@startuml migration

participant api
database db

api -> api : read migration files
api -> db : fetch migration histories
db --> api
api -> db : insert semaphore record
loop
    api -> db : migration
end
api -> db : delete semaphore record

@enduml
