FROM public.ecr.aws/lambda/provided:al2023 AS runtime

WORKDIR /app

RUN dnf install -y \
    openssl-devel \
    && rm -rf /var/cache/dnf/* \
    && dnf clean all

COPY ./conf/migrations ./conf/migrations
COPY ./bin/omnius-opxs-api ${LAMBDA_RUNTIME_DIR}/bootstrap

CMD [ "lambda-handler" ]
