FROM debian:buster-slim AS runtime

WORKDIR /app

RUN apt-get update && apt-get install -y \
    pkg-config \
    libssl-dev \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

COPY ./conf ./conf
COPY ./migrations ./migrations
COPY ./bin/opxs-api /usr/local/bin/

ENTRYPOINT ["/usr/local/bin/opxs-api"]
