FROM public.ecr.aws/lambda/provided:al2023 AS runtime

WORKDIR /app

RUN dnf install -y \
    openssl-devel \
    && rm -rf /var/cache/dnf/* \
    && dnf clean all

COPY ./bin/opxs-batch-email-send-feedback ${LAMBDA_RUNTIME_DIR}/bootstrap

CMD [ "lambda-handler" ]
