FROM public.ecr.aws/lambda/provided:al2 AS runtime

WORKDIR /app

RUN yum install -y \
    openssl-devel \
    pkg-config \
    && rm -rf /var/cache/yum/* \
    && yum clean all

COPY ./conf ./conf
COPY ./migrations ./migrations
COPY ./bin/batch/opxs-batch-send-email-feedback /usr/local/bin/

ENTRYPOINT ["/usr/local/bin/opxs-batch-send-email-feedback"]
