FROM public.ecr.aws/lambda/provided:al2 AS runtime

WORKDIR /app

RUN yum install -y \
    openssl-devel \
    && rm -rf /var/cache/yum/* \
    && yum clean all

COPY ./bin/batch/opxs-batch-email-send ${LAMBDA_RUNTIME_DIR}/bootstrap

CMD [ "lambda-handler" ]
