FROM public.ecr.aws/lambda/provided:al2 AS runtime

WORKDIR /app

COPY ./conf ./conf
COPY ./migrations ./migrations
COPY ./bin/opxs-batch-email-bounce /usr/local/bin/

ENTRYPOINT ["/usr/local/bin/opxs-batch-email-bounce"]
