[tasks.fmt-check]
workspace = false
install_crate = "rustfmt"
args = ["fmt", "--all", "--", "--check"]
command = "cargo"

[tasks.clippy]
workspace = false
install_crate = "clippy"
command = "cargo"
args = ["clippy", "--", "-D", "warnings", "-A", "unused"]

[tasks.lint]
workspace = false
dependencies = ["fmt-check", "clippy"]

[tasks.test]
command = "cargo"
args = ["test", "--all-features"]
dependencies = ["lint"]

[tasks.watch]
workspace = false
command = "cargo"
install_crate = "cargo-watch"
args = ["watch", "-x", "run --bin omnius-opxs-api"]
