###
GET http://localhost:9080/counter

###
POST http://localhost:9080/counter/increment
content-type: application/json

{
    "value": 10
}

###
POST http://localhost:9080/counter/decrement
content-type: application/json

{
    "value": 10
}

###
POST http://localhost:9080/counter/reset
